/*
 * Code generated by openapi-generator. DO NOT EDIT.
 * source: openapi/specs/openapi.yaml
 */

package openapi

type ErrorResponse struct {
	Code int32 `json:"code"`

	Message string `json:"message"`
}
