/*
 * Code generated by openapi-generator. DO NOT EDIT.
 * source: openapi/specs/openapi.yaml
 */

package openapi

type LoginRequest struct {
	Email string `json:"email"`

	Password string `json:"password"`
}
