/*
 * Code generated by openapi-generator. DO NOT EDIT.
 * source: openapi/specs/openapi.yaml
 */

package openapi

type LoginResponse struct {
	AccessToken string `json:"accessToken,omitempty"`

	RefreshToken string `json:"refreshToken,omitempty"`
}
