/*
 * Mwrooth API
 * This is the full api specification for the Mwrooth mobile app
 *
 * NOTE: Code generated by openapi-generator. DO NOT EDIT.
 * source: openapi/specs/openapi.yaml
 */
 
package openapi

import (
	"context"
	"github.com/gin-gonic/gin"
	"net/http"
)

// ContextHandler the handler type that allows access to the current go and gin context
type ContextHandler func(ctx context.Context, c *gin.Context)

// Route is the information for every URI.
type Route struct {
	// Name is the name of this Route.
	Name string
	// Method is the string for the HTTP method. ex) GET, POST etc..
	Method string
	// Pattern is the pattern of the URI.
	Pattern string
	// HandlerFunc is the handler function of this route.
	HandlerFunc ContextHandler
}

const (
	// IndexEndpoint the path of the Index endpoint
	IndexEndpoint = "/v1/"

	// LoginEndpoint the path of the Login endpoint
	LoginEndpoint = "/v1/auth/login"
)

// Routes is the list of the generated Route.
type Routes []Route

// CreateRoutes creates the routes of the given router
func CreateRoutes(router Router) Routes {
    return Routes{
		{
			Name:        "Index",
			Method:      http.MethodGet,
			Pattern:     IndexEndpoint,
			HandlerFunc: router.Index(),
		},
		{
			Name:        "Login",
			Method:      http.MethodPost,
			Pattern:     LoginEndpoint,
			HandlerFunc: router.Login(),
		},
    }
}

// Router the router that defines the gateway
type Router interface {
	// Index
	Index() ContextHandler

	// Login Login
	Login() ContextHandler
}
